use master;
alter database BDAlterTable set single_user with rollback immediate;
drop database if exists BDAlterTable;
go

create database BDAlterTable;
go

use BDAlterTable;
go

if object_id('INSCRIPCIONES', 'U') is not null drop table INSCRIPCIONES;
if object_id('CURSOS', 'U') is not null drop table CURSOS;
if object_id('ESTUDIANTES', 'U') is not null drop table ESTUDIANTES;
go

CREATE TABLE ESTUDIANTES (
    ID_ESTUDIANTE INT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    FECHA_NACIMIENTO DATE
);
go

CREATE TABLE CURSOS (
    ID_CURSO INT PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(100),
    DESCRIPCION VARCHAR(255),
    DURACION DECIMAL(5,1), -- Corrección de tipo de dato
    PRECIO DECIMAL(10, 2)
);
go

CREATE TABLE INSCRIPCIONES (
    ID_INSCRIPCION INT PRIMARY KEY,
    ID_ESTUDIANTE INT,
    ID_CURSO INT,
    FECHA_INSCRIPCION DATE NOT NULL, -- Corrección para NOT NULL
    CALIFICACION INT,
    CONSTRAINT FK_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE),
    CONSTRAINT FK_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO),
    CONSTRAINT UC_ESTUDIANTE_CURSO UNIQUE (ID_ESTUDIANTE, ID_CURSO)
);
go

ALTER TABLE ESTUDIANTES ADD DIRECCION VARCHAR(200);
go

ALTER TABLE CURSOS ALTER COLUMN DURACION DECIMAL(5,1);
go

ALTER TABLE INSCRIPCIONES ALTER COLUMN FECHA_INSCRIPCION DATE NOT NULL;
go

ALTER TABLE CURSOS ADD CONSTRAINT UQ_NOMBRE_CURSO UNIQUE (NOMBRE_CURSO);
go

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CK_FECHA_NACIMIENTO CHECK (FECHA_NACIMIENTO <= DATEADD(YEAR, -16, GETDATE()));
go

ALTER TABLE INSCRIPCIONES DROP CONSTRAINT FK_ESTUDIANTE;

-- 2. Crear la clave foránea con ON UPDATE CASCADE
ALTER TABLE INSCRIPCIONES 
ADD CONSTRAINT FK_ESTUDIANTE 
FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE) 
ON UPDATE CASCADE;
go

ALTER TABLE CURSOS ADD CONSTRAINT CK_PRECIO CHECK (PRECIO >= 0);
go

ALTER TABLE ESTUDIANTES DROP CONSTRAINT CK_FECHA_NACIMIENTO;
go

ALTER TABLE ESTUDIANTES DROP COLUMN FECHA_NACIMIENTO;
go

EXEC sp_rename 'INSCRIPCIONES.CALIFICACION', 'PUNTUACION', 'COLUMN';
go

SELECT name 
FROM sys.key_constraints 
WHERE type = 'UQ' AND parent_object_id = OBJECT_ID('CURSOS');
go

ALTER TABLE CURSOS DROP CONSTRAINT UQ_NOMBRE_CURSO;
go

ALTER TABLE CURSOS ADD CONSTRAINT UQ_NOMBRE_CURSO UNIQUE (NOMBRE_CURSO);
go